<?php 
// These are some default watch terms for Juniper to sniff out
// Got anymore to suggest? Email tyrone@jacksonwhelan.com

$watchlist = array(
	'dowload movies',
	'download movies',
	' rx ',
	'xenical',
	'pharma ',
	'hoodia',
	'minoxidil',
	'vardenafil',
	'retin-a',
	'retin a',
	'accutane',
	'<h5><script',
	' cialis',
	'viagra ',
	'propecia',
	'pharmacy',
	'prescription',
	'levitra',
	'zoloft',
	'lasix',
	'prescriptions',
	'perscribtion',
	'yaz',
	'vytorin',
	'tramadol',
	'<code_update_ok>',
	'lexapro',
	'prozac',
	'lipitor',
	'ae.awaue.com',
	'ie.eracou.com',
	'vicodin',
	'main.js',
	'/wp.js',
	'ciprofloxacin',
	'yagara',
	'levlen',
	'skelaxin',
	'zimulti',
	'antivert',
	'mircette',
	'superpuperdomain',
	'counter-wordpress',
	'.ru',
	'.pl',
	'.us.to',
	'googlesafebrowsing',
	'Cannot modify header information'
);
?>